export const OdrlPolicy = {
    id: 0,
    policyType: "Agreement",
    target: "",
    provider: "My party",
    consumer: "",

    location_input: [""],
    location_op: "",
    application_input: [""],
    application_op: "",
    connector_input: [""],
    connector_op: "",
    role_input: [""],
    role_op: "", 
    purpose_input: [""],
    purpose_op: "",
    event_input: [""],
    event_op: "",
    state_input: [""],
    state_op: "",
    securityLevel_input: [""],
    securityLevel_op: "",

    preduties_systemDevice: "",
    preduties_logLevel: "",
    preduties_durationYear: "",
    preduties_durationMonth: "",
    preduties_durationDay: "",
    preduties_durationHour: "",
    preduties_timeAndDate: "",
    preduties_notificationLevel: "",
    preduties_informedParty: "",

    postduties_systemDevice: "",
    postduties_logLevel: "",
    postduties_durationYear: "",
    postduties_durationMonth: "",
    postduties_durationDay: "",
    postduties_durationHour: "",
    postduties_timeAndDate: "",
    postduties_notificationLevel: "",
    postduties_informedParty: "",

    system: "",
    interval: "",
    payment: "",
    price: "",
    counter: "",
    encoding: "",
    policy: "",
    time: "",
    timeUnit: "",
    timeAndDate: "",
    informedParty:"",
    systemDevice:"",
    valueToChange: "",
    modifier: "",
    fieldToChange: "",
    restrictTimeIntervalStart:"",
    restrictTimeIntervalEnd: "",
    restrictEndTime: "",
    specifyBeginTime:"",
    durationHour: "",
    durationDay: "",
    durationMonth: "",
    durationYear: "",
    logLevel:"",
    notificationLevel:"",
    artifactState:"",
  };