export const OdrlPolicy = {
    id: 0,
    policyType: "Agreement",
    target: "",
    provider: "My party",
    consumer: "",
    location: { input: [""], op: "" },
    system: "",
    application:{ input: [""], op: "" },
    connector:{ input: [""], op: "" },
    role:{ input: [""], op: "" },
    purpose: {  input: [""], op: ""},
    event: { input: [""], op: "" },
    state:{ input: [""], op: "" },
    interval: "",
    payment: "",
    price: "",
    counter: "",
    encoding: "",
    securityLevel: { input: [""], op: "" },
    policy: "",
    time: "",
    timeUnit: "",
    timeAndDate: "",
    informedParty:"",
    systemDevice:"",
    valueToChange: "",
    modifier: "",
    fieldToChange: "",
    restrictTimeIntervalStart:"",
    restrictTimeIntervalEnd: "",
    restrictEndTime: "",
    specifyBeginTime:"",
    durationHour: "",
    durationDay: "",
    durationMonth: "",
    durationYear: "",
    logLevel:"",
    notificationLevel:"",
    artifactState:"",
  };

  export const OdrlPolicyZero = {
    id: 0,
    policyType: "Agreement",
    target: "",
    provider: "My party",
    consumer: "",
    location: { input: [""], op: "" },
    system: "",
    application:{ input: [""], op: "" },
    connector:{ input: [""], op: "" },
    role:{ input: [""], op: "" },
    purpose: {  input: [""], op: ""},
    event: { input: [""], op: "" },
    state:{ input: [""], op: "" },
    interval: "",
    payment: "",
    price: "",
    counter: "",
    encoding: "",
    securityLevel: { input: [""], op: "" },
    policy: "",
    time: "",
    timeUnit: "",
    timeAndDate: "",
    informedParty:"",
    systemDevice:"",
    valueToChange: "",
    modifier: "",
    fieldToChange: "",
    restrictTimeIntervalStart:"",
    restrictTimeIntervalEnd: "",
    restrictEndTime: "",
    specifyBeginTime:"",
    durationHour: "",
    durationDay: "",
    durationMonth: "",
    durationYear: "",
    logLevel:"",
    notificationLevel:"",
    artifactState:"",
  };