export const OdrlPolicy = {
    id: 0,
    policyType: "Agreement",
    target: "",
    provider: "My party",
    consumer: "",
    location: "",
    system: "",
    application:"",
    connector:"",
    role:"",
    purpose: "",
    event: "",
    state:"",
    interval: "",
    payment: "",
    price: "",
    counter: "",
    encoding: "",
    securityLevel: "",
    policy: "",
    time: "",
    timeUnit: "",
    timeAndDate: "",
    informedParty:"",
    systemDevice:"",
    valueToChange: "",
    modifier: "",
    fieldToChange: "",
    restrictTimeIntervalStart:"",
    restrictTimeIntervalEnd: "",
    restrictEndTime: "",
    specifyBeginTime:"",
    durationHour: "",
    durationDay: "",
    durationMonth: "",
    durationYear: "",
    logLevel:"",
    notificationLevel:"",
    artifactState:"",
  };