package pages.base

abstract class CorrectPolicies {
    static String provideAccess() {
        return ' {       \"@context\": {\"@context\"      \"ids\":\"https://w3id.org/idsa/core/\",\"ids\"\"https://w3id.org/idsa/core/\"      \"idsc\" : \"https://w3id.org/idsa/code/\"\"idsc\"\"https://w3id.org/idsa/code/\"   },      \"@type\": \"ids:ContractAgreement\",    \"@type\"\"ids:ContractAgreement\"  \"@id\": \"https://w3id.org/idsa/autogen/contract/restrict-access\",    \"@id\"\"https://w3id.org/idsa/autogen/contract/restrict-access\"  \"profile\": \"http://example.com/ids-profile\",    \"profile\"\"http://example.com/ids-profile\"  \"ids:target\": {\"ids:target\"      \"@id\":\"http://example.com\"\"@id\"\"http://example.com\"   },      \"ids:provider\": \"http://example.com/party/my-party\",    \"ids:provider\"\"http://example.com/party/my-party\"  \"ids:consumer\": \"http://example.com/party/consumer-party\",    \"ids:consumer\"\"http://example.com/party/consumer-party\"  \"ids:permission\": [{    \"ids:permission\"      \"ids:action\": [{\"ids:action\"        \"@id\":\"idsc:USE\"\"@id\"\"idsc:USE\"      }]  }] } '
    }
    static String provideAccessWithLocation() {
        return ' {       "@context": {"@context"      "ids":"https://w3id.org/idsa/core/","ids""https://w3id.org/idsa/core/"      "idsc" : "https://w3id.org/idsa/code/""idsc""https://w3id.org/idsa/code/"   },      "@type": "ids:ContractAgreement",    "@type""ids:ContractAgreement"  "@id": "https://w3id.org/idsa/autogen/contract/restrict-access-location",    "@id""https://w3id.org/idsa/autogen/contract/restrict-access-location"  "profile": "http://example.com/ids-profile",    "profile""http://example.com/ids-profile"  "ids:target": {"ids:target"      "@id":"http://example.com""@id""http://example.com"   },      "ids:provider": "http://example.com/party/my-party",    "ids:provider""http://example.com/party/my-party"  "ids:consumer": "http://example.com/party/consumer-party",    "ids:consumer""http://example.com/party/consumer-party"  "ids:permission": [{    "ids:permission"      "ids:action": [{"ids:action"        "@id":"idsc:USE""@id""idsc:USE"      }],           "ids:constraint": [{    "ids:constraint"        "@type":"ids:Constraint",  "@type""ids:Constraint"        "ids:pipEndpoint": { "@id": "https//example.com/pip/absolutespatialposition" } "ids:pipEndpoint""@id""https//example.com/pip/absolutespatialposition"      }     ]   }] } '
    }
    static String provideAccessWithSystem() {
        return ' {       "@context": {"@context"      "ids":"https://w3id.org/idsa/core/","ids""https://w3id.org/idsa/core/"      "idsc" : "https://w3id.org/idsa/code/""idsc""https://w3id.org/idsa/code/"   },      "@type": "ids:ContractAgreement",    "@type""ids:ContractAgreement"  "@id": "https://w3id.org/idsa/autogen/contract/restrict-access-purpose",    "@id""https://w3id.org/idsa/autogen/contract/restrict-access-purpose"  "profile": "http://example.com/ids-profile",    "profile""http://example.com/ids-profile"  "ids:target": {"ids:target"      "@id":"http://example.com""@id""http://example.com"   },      "ids:provider": "http://example.com/party/my-party",    "ids:provider""http://example.com/party/my-party"  "ids:consumer": "http://example.com/party/consumer-party",    "ids:consumer""http://example.com/party/consumer-party"  "ids:permission": [{    "ids:permission"      "ids:action": [{"ids:action"        "@id":"idsc:USE""@id""idsc:USE"      }],           "ids:constraint": [{    "ids:constraint"        "@type":"ids:Constraint",  "@type""ids:Constraint"        "ids:pipEndpoint": { "@id": "https//example.com/pip/purpose" } "ids:pipEndpoint""@id""https//example.com/pip/purpose"      }     ]   }] } '

    }
    static String provideAccessWithInterval(startTime, endTime) {
        return ' {       "@context": {"@context"      "ids":"https://w3id.org/idsa/core/","ids""https://w3id.org/idsa/core/"      "idsc" : "https://w3id.org/idsa/code/""idsc""https://w3id.org/idsa/code/"   },      "@type": "ids:ContractAgreement",    "@type""ids:ContractAgreement"  "@id": "https://w3id.org/idsa/autogen/contract/restrict-access-interval",    "@id""https://w3id.org/idsa/autogen/contract/restrict-access-interval"  "profile": "http://example.com/ids-profile",    "profile""http://example.com/ids-profile"  "ids:target": {"ids:target"      "@id":"http://example.com""@id""http://example.com"   },      "ids:provider": "http://example.com/party/my-party",    "ids:provider""http://example.com/party/my-party"  "ids:consumer": "http://example.com/party/consumer-party",    "ids:consumer""http://example.com/party/consumer-party"  "ids:permission": [{    "ids:permission"      "ids:action": [{"ids:action"        "@id":"idsc:USE""@id""idsc:USE"      }],           "ids:constraint": [{    "ids:constraint"        "@type":"ids:Constraint",  "@type""ids:Constraint"         "@type": "ids:interval", "@type""ids:interval"         "@value": { "@value"             "ids:begin": {"ids:begin"               "@value": "2021-02-09T15:02Z","@value""2021-02-09T15:02Z"               "@type": "xsd:datetimeStamp""@type""xsd:datetimeStamp"            }, '

        }
}