export const OdrlPolicy = {
    id: 0,
    policyType: "",
    target: "",
    provider: "My party",
    consumer: "",
    location: "",
    system: "",
    purpose: "",
    event: "",
    interval: "",
    payment: "",
    price: "",
    counter: "",
    encoding: "",
    policy: "",
    time: "",
    timeUnit: "",
    timeAndDate: "",
    informedParty:"",
    systemDevice:"",
    valueToChange: "",
    modificator: "",
    fieldToChange: "",
    restrictTimeIntervalStart:"",
    restrictTimeIntervalEnd: "",
  };